# Generated by Django 3.2.5 on 2021-08-12 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='npv_total',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Total', models.CharField(max_length=150)),
                ('TradeType', models.CharField(max_length=150)),
                ('Maturity', models.CharField(max_length=150)),
                ('MaturityTime', models.CharField(max_length=150)),
                ('NPV', models.CharField(max_length=150)),
                ('NpvCurrency', models.CharField(max_length=150)),
                ('NPV_Base', models.FloatField()),
                ('BaseCurrency', models.CharField(max_length=150)),
                ('CE_Base', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
