# Generated by Django 3.2.6 on 2021-08-13 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvApp', '0004_dates'),
    ]

    operations = [
        migrations.CreateModel(
            name='npv_creditrating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Creditrating', models.CharField(max_length=150)),
                ('TradeType', models.CharField(max_length=150)),
                ('Maturity', models.CharField(max_length=150)),
                ('MaturityTime', models.CharField(max_length=150)),
                ('NPV', models.CharField(max_length=150)),
                ('NpvCurrency', models.CharField(max_length=150)),
                ('NPV_Base', models.FloatField()),
                ('BaseCurrency', models.CharField(max_length=150)),
                ('CE_Base', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='npv_nettingset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nettingset', models.CharField(max_length=150)),
                ('TradeType', models.CharField(max_length=150)),
                ('Maturity', models.CharField(max_length=150)),
                ('MaturityTime', models.CharField(max_length=150)),
                ('NPV', models.CharField(max_length=150)),
                ('NpvCurrency', models.CharField(max_length=150)),
                ('NPV_Base', models.FloatField()),
                ('BaseCurrency', models.CharField(max_length=150)),
                ('CE_Base', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='npv_trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade', models.CharField(max_length=150)),
                ('TradeType', models.CharField(max_length=150)),
                ('Maturity', models.CharField(max_length=150)),
                ('MaturityTime', models.CharField(max_length=150)),
                ('NPV', models.CharField(max_length=150)),
                ('NpvCurrency', models.CharField(max_length=150)),
                ('NPV_Base', models.FloatField()),
                ('BaseCurrency', models.CharField(max_length=150)),
                ('CE_Base', models.FloatField()),
            ],
        ),
    ]
