# Generated by Django 3.2.6 on 2021-08-14 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csvApp', '0005_npv_creditrating_npv_nettingset_npv_trade'),
    ]

    operations = [
        migrations.AddField(
            model_name='npv_counterparty',
            name='id_date',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='csvApp.dates'),
        ),
        migrations.AddField(
            model_name='npv_creditrating',
            name='id_date',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='csvApp.dates'),
        ),
        migrations.AddField(
            model_name='npv_nettingset',
            name='id_date',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='csvApp.dates'),
        ),
        migrations.AddField(
            model_name='npv_total',
            name='id_date',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='csvApp.dates'),
        ),
        migrations.AddField(
            model_name='npv_trade',
            name='id_date',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='csvApp.dates'),
        ),
    ]
