# Generated by Django 3.2.6 on 2021-08-14 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvApp', '0006_auto_20210814_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dates',
            name='date',
            field=models.CharField(max_length=150),
        ),
    ]
