# Generated by Django 3.2.6 on 2021-08-15 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvApp', '0008_auto_20210815_1511'),
    ]

    operations = [
        migrations.CreateModel(
            name='xpv_total',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('TradeId', models.CharField(max_length=150)),
                ('Total', models.CharField(max_length=150)),
                ('CVA', models.FloatField()),
                ('DVA', models.FloatField()),
                ('FBA', models.FloatField()),
                ('FCA', models.FloatField()),
                ('COLVA', models.FloatField()),
                ('CollateralFloor', models.FloatField()),
                ('AllocatedCVA', models.FloatField()),
                ('AllocatedDVA', models.FloatField()),
                ('AllocationMethod', models.CharField(max_length=150)),
                ('BaselEPE', models.FloatField()),
                ('BaselEEPE', models.FloatField()),
            ],
        ),
    ]
