# Generated by Django 3.2.6 on 2021-08-15 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvApp', '0009_xpv_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='exposeur_total',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Total', models.CharField(max_length=150)),
                ('Date', models.DateField(null=True)),
                ('Time', models.CharField(max_length=150)),
                ('EPE', models.FloatField()),
                ('ENE', models.FloatField()),
                ('PFE', models.FloatField()),
                ('ExpectedCollateral', models.FloatField()),
                ('BaselEE', models.FloatField()),
                ('BaselEEE', models.FloatField()),
            ],
        ),
    ]
