# Generated by Django 3.2.6 on 2021-08-16 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvApp', '0010_exposeur_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='xpv_counterparty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('TradeId', models.CharField(max_length=150)),
                ('Counterparty', models.CharField(max_length=150)),
                ('CVA', models.FloatField()),
                ('DVA', models.FloatField()),
                ('FBA', models.FloatField()),
                ('FCA', models.FloatField()),
                ('COLVA', models.FloatField()),
                ('CollateralFloor', models.FloatField()),
                ('AllocatedCVA', models.FloatField()),
                ('AllocatedDVA', models.FloatField()),
                ('AllocationMethod', models.CharField(max_length=150)),
                ('BaselEPE', models.FloatField()),
                ('BaselEEPE', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='xpv_creditrating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('TradeId', models.CharField(max_length=150)),
                ('CreditRating', models.CharField(max_length=150)),
                ('CVA', models.FloatField()),
                ('DVA', models.FloatField()),
                ('FBA', models.FloatField()),
                ('FCA', models.FloatField()),
                ('COLVA', models.FloatField()),
                ('CollateralFloor', models.FloatField()),
                ('AllocatedCVA', models.FloatField()),
                ('AllocatedDVA', models.FloatField()),
                ('AllocationMethod', models.CharField(max_length=150)),
                ('BaselEPE', models.FloatField()),
                ('BaselEEPE', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='xpv_nettingset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('TradeId', models.CharField(max_length=150)),
                ('Nettingset', models.CharField(max_length=150)),
                ('CVA', models.FloatField()),
                ('DVA', models.FloatField()),
                ('FBA', models.FloatField()),
                ('FCA', models.FloatField()),
                ('COLVA', models.FloatField()),
                ('CollateralFloor', models.FloatField()),
                ('AllocatedCVA', models.FloatField()),
                ('AllocatedDVA', models.FloatField()),
                ('AllocationMethod', models.CharField(max_length=150)),
                ('BaselEPE', models.FloatField()),
                ('BaselEEPE', models.FloatField()),
            ],
        ),
    ]
