# Generated by Django 3.2.6 on 2021-08-19 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvApp', '0011_xpv_counterparty_xpv_creditrating_xpv_nettingset'),
    ]

    operations = [
        migrations.CreateModel(
            name='Limits_Counterparty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Limits', models.CharField(max_length=150)),
                ('NPV', models.CharField(max_length=150)),
                ('CE', models.FloatField()),
                ('EEPE', models.FloatField()),
                ('Total_Exposeur', models.CharField(max_length=150)),
                ('ColVA', models.CharField(max_length=150)),
                ('CVA', models.FloatField()),
                ('DVA', models.FloatField()),
                ('FCA', models.FloatField()),
                ('FBA', models.FloatField()),
                ('FVA', models.FloatField()),
                ('IM', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Limits_CreditRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Limits', models.CharField(max_length=150)),
                ('NPV', models.CharField(max_length=150)),
                ('CE', models.FloatField()),
                ('EEPE', models.FloatField()),
                ('Total_Exposeur', models.CharField(max_length=150)),
                ('ColVA', models.CharField(max_length=150)),
                ('CVA', models.FloatField()),
                ('DVA', models.FloatField()),
                ('FCA', models.FloatField()),
                ('FBA', models.FloatField()),
                ('FVA', models.FloatField()),
                ('IM', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Limits_Nettingset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Limits', models.CharField(max_length=150)),
                ('NPV', models.CharField(max_length=150)),
                ('CE', models.FloatField()),
                ('EEPE', models.FloatField()),
                ('Total_Exposeur', models.CharField(max_length=150)),
                ('ColVA', models.CharField(max_length=150)),
                ('CVA', models.FloatField()),
                ('DVA', models.FloatField()),
                ('FCA', models.FloatField()),
                ('FBA', models.FloatField()),
                ('FVA', models.FloatField()),
                ('IM', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Limits_Total',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Limits', models.CharField(max_length=150)),
                ('NPV', models.CharField(max_length=150)),
                ('CE', models.FloatField()),
                ('EEPE', models.FloatField()),
                ('Total_Exposeur', models.CharField(max_length=150)),
                ('ColVA', models.CharField(max_length=150)),
                ('CVA', models.FloatField()),
                ('DVA', models.FloatField()),
                ('FCA', models.FloatField()),
                ('FBA', models.FloatField()),
                ('FVA', models.FloatField()),
                ('IM', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Limits_Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Limits', models.CharField(max_length=150)),
                ('NPV', models.CharField(max_length=150)),
                ('CE', models.FloatField()),
                ('EEPE', models.FloatField()),
                ('Total_Exposeur', models.CharField(max_length=150)),
                ('ColVA', models.CharField(max_length=150)),
                ('CVA', models.FloatField()),
                ('DVA', models.FloatField()),
                ('FCA', models.FloatField()),
                ('FBA', models.FloatField()),
                ('FVA', models.FloatField()),
                ('IM', models.CharField(max_length=150)),
            ],
        ),
    ]
