# Generated by Django 3.2.6 on 2021-08-19 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvApp', '0013_auto_20210819_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limits_total',
            name='CVA',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='limits_total',
            name='DVA',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='limits_total',
            name='FBA',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='limits_total',
            name='FCA',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='limits_total',
            name='FVA',
            field=models.FloatField(),
        ),
    ]
