# Generated by Django 3.2.6 on 2021-08-19 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvApp', '0014_auto_20210819_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limits_trade',
            name='CVA',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='limits_trade',
            name='DVA',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='limits_trade',
            name='FBA',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='limits_trade',
            name='FCA',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='limits_trade',
            name='FVA',
            field=models.CharField(max_length=150),
        ),
    ]
