# Generated by Django 3.2.6 on 2021-08-20 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvApp', '0015_auto_20210819_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xpv_nettingset',
            name='AllocatedCVA',
            field=models.CharField(max_length=150),
        ),
    ]
