# Generated by Django 3.2.6 on 2021-08-23 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvApp', '0018_alter_xpv_nettingset_collateralfloor'),
    ]

    operations = [
        migrations.CreateModel(
            name='alldata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creditrating', models.CharField(max_length=255)),
                ('counterparty', models.CharField(max_length=255)),
                ('nettingset', models.CharField(max_length=255)),
                ('trade', models.CharField(max_length=255)),
                ('metrice', models.CharField(max_length=255)),
                ('limitValue', models.FloatField()),
                ('ConsumptionValue', models.FloatField()),
                ('date', models.DateField(null=True)),
                ('cons', models.FloatField()),
            ],
        ),
    ]
