# Generated by Django 3.2.6 on 2021-08-23 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvApp', '0019_alldata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alldata',
            name='cons',
            field=models.CharField(max_length=255),
        ),
    ]
