# Generated by Django 3.2.6 on 2021-08-23 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvApp', '0020_alter_alldata_cons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alldata',
            name='ConsumptionValue',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='alldata',
            name='date',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='alldata',
            name='limitValue',
            field=models.CharField(max_length=255),
        ),
    ]
