# Generated by Django 3.2.6 on 2021-08-24 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvApp', '0021_auto_20210823_2158'),
    ]

    operations = [
        migrations.CreateModel(
            name='alldata2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creditrating', models.CharField(max_length=255)),
                ('counterparty', models.CharField(max_length=255)),
                ('nettingset', models.CharField(max_length=255)),
                ('trade', models.CharField(max_length=255)),
                ('metrice', models.CharField(max_length=255)),
                ('limitValue', models.CharField(max_length=255)),
                ('ConsumptionValue', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=255, null=True)),
                ('cons', models.CharField(max_length=255)),
            ],
        ),
    ]
